name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., macOS 13.0, Ubuntu 22.04]
        - Python version: [e.g., 3.11.5]
        - Project version/commit: [e.g., v1.2.3 or commit abc123]
      value: |
        - OS:
        - Python version:
        - Project version/commit:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, paste any error messages or logs
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: documentation
    attributes:
      label: Documentation Reference
      description: If you consulted documentation, which docs did you check?
      placeholder: |
        - README.md section X
        - docs/api.md
        - No documentation found for this feature
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem
      placeholder: Any additional details...
